#from take5.survey.models import Survey, SurveyQuestion, SurveyQuestionAlternative, SurveyUserAnswer
from survey.models import Survey


test_survey = Survey( name = "1 2 3 testando..." )
question_1 = SurveyQuestion(  survey = test_survey , question_text = "O que voce come no cafe da manha?" )
q_1_a_1 = SurveyQuestionAlternative( question = question_1, text = "Suco de couve com maca e beterraba." ) 
q_1_a_2 = SurveyQuestionAlternative( question = question_1, text = "Pao com presunto" ) 
q_1_a_3 = SurveyQuestionAlternative( question = question_1, text = "Cuscus" ) 
q_1_a_4 = SurveyQuestionAlternative( question = question_1, text = "Eu nao como de manha pq faco jejum." ) 
q_1_a_5 = SurveyQuestionAlternative( question = question_1, text = "Eu nao como de manha pq acordo meio dia." ) 
test_survey.save()
question_1.save()
q_1_a_1.save()
q_1_a_2.save()
q_1_a_3.save()
q_1_a_4.save()
q_1_a_5.save()

question_2 = SurveyQuestion( survey = test_survey, question_text = "Qual a sua cor favorita ?" )
q_2_a_1 = SurveyQuestionAlternative( question = question_2, text = "Azul" ) 
q_2_a_2 = SurveyQuestionAlternative( question = question_2, text ="Vermelho" ) 
q_2_a_3 = SurveyQuestionAlternative( question = question_2, text ="Verde" ) 
q_2_a_4 = SurveyQuestionAlternative( question = question_2, text ="Amarelo" ) 
q_2_a_5 = SurveyQuestionAlternative( question = question_2, text ="Rosa" ) 
q_2_a_6 = SurveyQuestionAlternative( question = question_2, text ="Qualquer uma menos Rosa" ) 
question_2.save()
q_2_a_1.save()
q_2_a_2.save()
q_2_a_3.save()
q_2_a_4.save()
q_2_a_5.save()
q_2_a_6.save()

question_3 = SurveyQuestion( survey = test_survey, question_text = "Lula ou Bolsonaro ? cuidado com a resposta." )
q_3_a_1 = SurveyQuestionAlternative( question = question_3, text = "Lula" ) 
q_3_a_2 = SurveyQuestionAlternative( question = question_3, text = "Bolsonaro" ) 
q_3_a_3 = SurveyQuestionAlternative( question = question_3, text = "O voto eh secreto" )
q_3_a_4 = SurveyQuestionAlternative( question = question_3, text = "Nulos/brancos/envergonhados/indecisos" ) 
question_3.save()
q_3_a_1.save()
q_3_a_2.save()
q_3_a_3.save()
q_3_a_4.save()

question_4 = SurveyQuestion( survey = test_survey, question_text = "Complete a frase: A acupuntura eh ... " )
q_4_a_1 = SurveyQuestionAlternative( question = question_4, text = "uma ciencia milenar." ) 
q_4_a_2 = SurveyQuestionAlternative( question = question_4,  text = "um efeito placebo." ) 
q_4_a_3 = SurveyQuestionAlternative( question = question_4,  text = "eu nao sei o que eh isso." ) 
q_4_a_4 = SurveyQuestionAlternative( question = question_4,  text = "muito cara." ) 
question_4.save()
q_4_a_1.save()
q_4_a_2.save()
q_4_a_3.save()
q_4_a_4.save()


